/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2017-06-07 06:39:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Adminloginsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header.html", Long.valueOf(1440328481399L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<SCRIPT type=\"text/javascript\">   \r\n");
      out.write("window.history.forward();  \r\n");
      out.write("function noBack() \r\n");
      out.write("{\r\n");
      out.write("\twindow.history.forward();\r\n");
      out.write("\t} \r\n");
      out.write("\t</SCRIPT>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Apartment Management System</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"BackgroundImage.jpg\" style=\"overflow:hidden;\" onload=\"noBack();\"  \r\n");
      out.write("\tonpageshow=\"if (event.persisted) noBack();\" onunload=\"\">\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t\t");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"background:silver;text-align: center;font-size: 50px;height: 80%;\">\r\n");
      out.write("APARTMENT MANAGEMENT SYSTEM\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
String name=(String)request.getAttribute("Amin"); 
      out.write('\r');
      out.write('\n');
 if(name!=null) {
      out.write('\r');
      out.write('\n');
 session.setAttribute("user_name", name); 
      out.write(' ');
      out.write('\r');
      out.write('\n');
} 
      out.write("<br><br>\r\n");
      out.write("<center><font face=\"Arial\" size=4>WELCOME:");
      out.print(session.getAttribute("user_name"));
      out.write("</font></center>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<table align=\"right\">\r\n");
      out.write("<tr><td><input type=\"image\" id=\"myimage1\" style=\"height:30px;width:100px;\" src=\"logout.jpg\" onclick=\"location.href = 'HomeLogin.jsp';\"/></td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br><br>\r\n");
      out.write("<table>\t\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <style>\r\n");
      out.write("#bt-menu, #bt-menu ul {\r\n");
      out.write("margin: 0;\r\n");
      out.write("padding: 0;\r\n");
      out.write("list-style: none;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu {\r\n");
      out.write("width: 125%;\r\n");
      out.write("margin: 20px auto;\r\n");
      out.write("background: #DADFE1;\r\n");
      out.write("-moz-border-radius: 2px;\r\n");
      out.write("-webkit-border-radius: 2px;\r\n");
      out.write("-moz-box-shadow: 0 1px 1px #777;\r\n");
      out.write("-webkit-box-shadow: 0 1px 1px #777;\r\n");
      out.write("box-shadow: 0 1px 1px #777;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu:before,\r\n");
      out.write("#bt-menu:after {\r\n");
      out.write("content: \"\";\r\n");
      out.write("display: table;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu:after {\r\n");
      out.write("clear: both;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu {\r\n");
      out.write("zoom:1;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu li {\r\n");
      out.write("float: left;\r\n");
      out.write("-moz-box-shadow: 1px 0 0 #444;\r\n");
      out.write("-webkit-box-shadow: 1px 0 0 #444;\r\n");
      out.write("box-shadow: 1px 0 0 #444;\r\n");
      out.write("position: relative;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu a {\r\n");
      out.write("float: left;\r\n");
      out.write("padding: 10px 70px;\r\n");
      out.write("color: #000000;\r\n");
      out.write("text-transform: uppercase;\r\n");
      out.write("font: bold 12px Arial, Helvetica;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("text-shadow: 0 0px 0 #000;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu li:hover > a {\r\n");
      out.write("background: #333333;\r\n");
      out.write("color: #fafafa;\r\n");
      out.write("}\r\n");
      out.write("*html #bt-menu li a:hover { /* IE6 only */\r\n");
      out.write("color: #333333;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul {\r\n");
      out.write("margin: 70px 0 0 0;\r\n");
      out.write("_margin: 0; /*IE6 only*/\r\n");
      out.write("opacity: 0;\r\n");
      out.write("visibility: hidden;\r\n");
      out.write("position: absolute;\r\n");
      out.write("top: 38px;\r\n");
      out.write("left: 0;\r\n");
      out.write("z-index: 9999;\r\n");
      out.write("background: #DADFE1 url('images/pageglare.png') no-repeat scroll;\r\n");
      out.write(" -moz-border-radius: 3px;\r\n");
      out.write("-webkit-border-radius: 3px;\r\n");
      out.write("border-radius: 3px;\r\n");
      out.write("-webkit-transition: all .3s ease-in-out;\r\n");
      out.write("-moz-transition: all .3s ease-in-out;\r\n");
      out.write("-ms-transition: all .3s ease-in-out;\r\n");
      out.write("-o-transition: all .3s ease-in-out;\r\n");
      out.write("transition: all .3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu li:hover > ul {\r\n");
      out.write("opacity: 1;\r\n");
      out.write("visibility: visible;\r\n");
      out.write("margin: 0;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul ul {\r\n");
      out.write("top: 0;\r\n");
      out.write("left: 400px;\r\n");
      out.write("margin: 0 0 0 10px;\r\n");
      out.write("_margin: 0; /*IE6 only*/\r\n");
      out.write("-moz-box-shadow: -1px 0 0 rgba(255,255,255,.3);\r\n");
      out.write("-webkit-box-shadow: -1px 0 0 rgba(255,255,255,.3);\r\n");
      out.write("box-shadow: -1px 0 0 rgba(255,255,255,.3);\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul li {\r\n");
      out.write("float: none;\r\n");
      out.write("display: block;\r\n");
      out.write("border: 0;\r\n");
      out.write("_line-height: 0; /*IE6 only*/\r\n");
      out.write("-moz-box-shadow: 0 1px 0 #111, 0 2px 0 #666;\r\n");
      out.write("-webkit-box-shadow: 0 1px 0 #111, 0 2px 0 #666;\r\n");
      out.write("box-shadow: 0 1px 0 #111, 0 2px 0 #666;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul li:last-child {\r\n");
      out.write("-moz-box-shadow: none;\r\n");
      out.write("-webkit-box-shadow: none;\r\n");
      out.write("box-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul a {\r\n");
      out.write("padding: 10px;\r\n");
      out.write("width: 130px;\r\n");
      out.write("_height: 6px; /*IE6 only*/\r\n");
      out.write("display: block;\r\n");
      out.write("white-space: nowrap;\r\n");
      out.write("float: none;\r\n");
      out.write("text-transform: none;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul a:hover {\r\n");
      out.write("background-color: #333333;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul li:first-child > a {\r\n");
      out.write("-moz-border-radius: 3px 3px 0 0;\r\n");
      out.write("-webkit-border-radius: 3px 3px 0 0;\r\n");
      out.write("border-radius: 3px 3px 0 0;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul li:first-child > a:after {\r\n");
      out.write("content: '';\r\n");
      out.write("position: absolute;\r\n");
      out.write("left: 40px;\r\n");
      out.write("top: -6px;\r\n");
      out.write("border-left: 6px solid transparent;\r\n");
      out.write("border-right: 6px solid transparent;\r\n");
      out.write("border-bottom: 6px solid #333333;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul ul li:first-child a:after {\r\n");
      out.write("left: -6px;\r\n");
      out.write("top: 50%;\r\n");
      out.write("margin-top: -6px;\r\n");
      out.write("border-left: 0;\r\n");
      out.write("border-bottom: 6px solid transparent;\r\n");
      out.write("border-top: 6px solid transparent;\r\n");
      out.write("border-right: 4px solid #333333;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul li:first-child a:hover:after {\r\n");
      out.write("border-bottom-color: #DADFE1;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul ul li:first-child a:hover:after {\r\n");
      out.write("border-right-color: #DADFE1;\r\n");
      out.write("border-bottom-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("#bt-menu ul li:last-child > a {\r\n");
      out.write("-moz-border-radius: 0 0 2px 2px;\r\n");
      out.write("-webkit-border-radius: 0 0 3px 3px;\r\n");
      out.write("border-radius: 0 0 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<tr><td>\r\n");
      out.write("<ul id=\"bt-menu\"> \r\n");
      out.write("<li><a href=\"FlatRegistration.jsp\">Flat Registration</a></li> \r\n");
      out.write("<li> \r\n");
      out.write("<a href=\"SearchApartments.jsp\">Search Apartments</a> </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"ChooseHouse.jsp\">Tenant Registration</a></li> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<li><a href=\"Pay1.jsp\">Payments</a></li>\r\n");
      out.write("<li><a href=\"vacanthouse.jsp\">Vacate House</a></li> \r\n");
      out.write("</li> \r\n");
      out.write(" ");
 if(request.getAttribute("success")!=null) 
	{
      out.write("\r\n");
      out.write("\t\t\t<tr><td><font face=\"Arial\" color=\"green\" size=5>");
      out.print( request.getAttribute("success") );
      out.write("</font></td></tr>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write(" </ul>\r\n");
      out.write(" </td></tr>\r\n");
      out.write(" \r\n");
      out.write(" </table>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
