/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2017-06-07 06:40:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FlatRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<table align=\"right\">\r\n");
      out.write("<tr><td></td>\r\n");
      out.write("<td><input type=\"image\" id=\"myimage1\" style=\"height:30px;width:100px;\" src=\"logout.jpg\" onclick=\"location.href = 'HomeLogin.jsp';\"/></td></tr>\r\n");
      out.write("<tr><td></td>\r\n");
      out.write("<td><input type=\"image\" id=\"myimage\" style=\"height:30px;width:100px;\" src=\"homee.jpg\" onclick=\"location.href = 'Adminloginsuccess.jsp';\"/></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<SCRIPT type=\"text/javascript\">   \r\n");
      out.write("\r\n");
      out.write("\t</SCRIPT>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Register Flat</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"BackgroundImage.jpg\"  \r\n");
      out.write("\tonpageshow=\"if (event.persisted) noBack();\" onunload=\"\">\r\n");
      out.write("\t<center><p><font face=\"Arial\" size=20>Register Flats</font></p></center>\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"FlatRegistrationController\" method=\"post\">\r\n");
      out.write("\t\t<table align=\"center\">\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Flat Type</td><td><select name=\"typeId\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"1B\">1BHK</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"2B\">2BHK</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Flat Category</td><td><select name=\"flat_category\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Non-Furnished\">Non-Furnished</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Semi-Furnished\">Semi-Furnished</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Furnished\">Furnished</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Block Name:</td><td><select name=\"BlockName\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Pearl\">Pearl</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Emerald\">Emerald</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Topaz\">Topaz</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Diamond\">Diamond</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Floor Number:</td><td><select name=\"floorNo\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Flat Number:</td><td><select name=\"flatNum\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Owner Name:</td><td><input type=\"text\" Name=\"OwnerName\"");
 if(request.getParameter("OwnerName")!=null) 
	{
      out.write("value=\"");
      out.print(request.getParameter("OwnerName"));
      out.write('"');
} 
      out.write("></td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Owner Contact:</td><td><input type=\"text\" Name=\"OwnerContact\"");
 if(request.getParameter("OwnerContact")!=null) 
	{
      out.write("value=\"");
      out.print(request.getParameter("OwnerContact"));
      out.write('"');
} 
      out.write("></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Year Of Construction:</td><td><input type=\"text\" name=\"yearOfConst\"");
 if(request.getParameter("yearOfConst")!=null) 
	{
      out.write("value=\"");
      out.print(request.getParameter("yearOfConst"));
      out.write('"');
} 
      out.write("></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Rent:</td><td><input type=\"text\" name=\"rent\"");
 if(request.getParameter("rent")!=null) 
	{
      out.write("value=\"");
      out.print(request.getParameter("rent"));
      out.write('"');
} 
      out.write("></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Advance(Number of Months):</td><td><input type=\"text\" name=\"advanceMonth\"");
 if(request.getParameter("advanceMonth")!=null) 
	{
      out.write("value=\"");
      out.print(request.getParameter("advanceMonth"));
      out.write('"');
} 
      out.write("></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>Address:</td><td><input type=\"text\" size=\"50\" name=\"AdressOfOwner\"");
 if(request.getParameter("AdressOfOwner")!=null) 
	{
      out.write("value=\"");
      out.print(request.getParameter("AdressOfOwner"));
      out.write('"');
} 
      out.write(">  </td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Status:</td><td><select name=\"flatStatus\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"vacant\">Vacant</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"occupied\">Occupied</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Proof:</td><td><select name=\"AddressProof\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Voter Id\">Voter Id</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Ration Card\">Ration Card</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Water Tax\">Water Tax</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"House Tax\">House Tax</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<option value=\"Employee Id Card\">Employee ID Card</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t</select> </td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td><td><input type=\"submit\" value=\"Register\" style=\"width: 80px; height: 25px;\"><input type=\"reset\" value=\"Reset\"style=\"width: 80px; height: 25px;\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 if(request.getAttribute("error")!=null) {
      out.write("\r\n");
      out.write("\t<table align=\"center\">\r\n");
      out.write("\t\t<tr><td><font color=\"red\">");
      out.print( request.getAttribute("error") );
      out.write("</font></td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
