/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2016-12-10 10:39:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EndSiteWeb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write("header {\r\n");
      out.write("    background-color:#07409b;\r\n");
      out.write("    color:#07409b;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    padding:2px;\t\r\n");
      out.write("     \r\n");
      out.write("}\r\n");
      out.write("nav {\r\n");
      out.write("    line-height:30px;\r\n");
      out.write("    background-color:#eeeeee;\r\n");
      out.write("    height:500px;\r\n");
      out.write("    width:150px;\r\n");
      out.write("    float:left;\r\n");
      out.write("    padding:5px;\t      \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside {\r\n");
      out.write("    line-height:30px;\r\n");
      out.write("    background-color:#eeeeee;\r\n");
      out.write("    height:500px;\r\n");
      out.write("    width:150px;\r\n");
      out.write("    float:right;\r\n");
      out.write("    padding:11px; \t \r\n");
      out.write("}\r\n");
      out.write("section {\r\n");
      out.write("    width:100px;\r\n");
      out.write("    float:left;\r\n");
      out.write("    padding:10px;\t \t \r\n");
      out.write("}\r\n");
      out.write("footer {\r\n");
      out.write("    background-color:#07409b;\r\n");
      out.write("    color:white;\r\n");
      out.write("    clear:both;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    padding:5px;\t \t \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/webPages/header.jsp", out, false);
      out.write("\t<!-- include at compile time -->\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- <iframe id = \"id_description_iframe\" src=\"https://www.yodlee.com/\" width=\"75%\" height=\"500\" frameborder=\"0\" scrolling=\"yes\"></iframe>\r\n");
      out.write(" --><aside>\r\n");
      out.write("<!-- <br><br><br>\r\n");
      out.write("<font size=\"3\">Site Not found..??<br></font>\r\n");
      out.write("\t<a href=\"startNsr.jsp\">\r\n");
      out.write("  \t\t<font color=\"blue\"> <b><u>Help us to develop</u></b></font>\r\n");
      out.write("\t</a> -->\r\n");
      out.write("</aside>\r\n");
      out.write("<footer><p> &copy;Envestnet Yodlee | Powered by THE DREAM BUILDERS</p></footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
